@echo off
echo Downloading 7-Zip...
powershell -Command "Invoke-WebRequest https://www.7-zip.org/a/7z2401-x64.exe -OutFile 7-Zip-installer.exe"
echo Downloading apktool.jar...
powershell -Command "Invoke-WebRequest https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.9.3.jar -OutFile apktool.jar"
echo Downloading uber-apk-signer.jar...
powershell -Command "Invoke-WebRequest https://github.com/patrickfav/uber-apk-signer/releases/download/v1.3.0/uber-apk-signer-1.3.0.jar -OutFile uber-apk-signer.jar"
echo Downloading patch...
powershell -Command "Invoke-WebRequest http://smudge.codes/files/Balatro-APK-Patch.zip -OutFile Balatro-APK-Patch.zip"
echo Downloading Love2D APK...
powershell -Command "Invoke-WebRequest https://github.com/love2d/love-android/releases/download/11.5a/love-11.5-android-embed.apk -OutFile love-11.5-android-embed.apk"
echo Downloading Java...
powershell -Command "Invoke-WebRequest https://javadl.oracle.com/webapps/download/AutoDL?BundleId=249553_4d245f941845490c91360409ecffb3b4 -OutFile java-install.exe"

echo Installing Java...
java-install.exe /s

echo Deleting java-install.exe...
del java-install.exe

echo Adding Java to path...
set path=%path%;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;

echo Installing 7-Zip...
7-Zip-installer.exe /S

echo Deleting 7-Zip-installer.exe...
del 7-Zip-installer.exe

echo Copying Balatro.exe...
xcopy "C:\Program Files (x86)\Steam\steamapps\common\Balatro\Balatro.exe" "Balatro.exe" /E /H /Y /V /-I

echo Extracting Balatro.exe...
"C:\Program Files\7-Zip\7z.exe" x Balatro.exe -oBalatro

echo Deleting Balatro.exe...
del Balatro.exe

echo Unpacking Love2D APK...
java.exe -jar -Xmx1024M -Duser.language=en -Dfile.encoding=UTF8 -Djdk.util.zip.disableZip64ExtraFieldValidation=true -Djdk.nio.zipfs.allowDotZipEntry=true "apktool.jar" d -s -o balatro-apk love-11.5-android-embed.apk

echo Deleting Love2D APK...
del love-11.5-android-embed.apk

echo Extracting patch...
"C:\Program Files\7-Zip\7z.exe" x Balatro-APK-Patch.zip -oBalatro-APK-Patch

echo Deleting patch zip...
del Balatro-APK-Patch.zip

echo Patching APK folder...
xcopy "Balatro-APK-Patch\" "balatro-apk\" /E /H /Y /V

echo Deleting patch...
rmdir Balatro-APK-Patch\ /S /Q

echo Patching globals.lua
notepad Balatro\globals.lua

echo Packing Balatro folder...
cd Balatro
"C:\Program Files\7-Zip\7z.exe" a balatro.zip
cd ..

echo Moving archive...
move Balatro\balatro.zip balatro-apk\assets\game.love

echo Deleting Balatro folder...
rmdir Balatro\ /S /Q

echo Repacking APK...
java.exe -jar -Xmx1024M -Duser.language=en -Dfile.encoding=UTF8 -Djdk.util.zip.disableZip64ExtraFieldValidation=true -Djdk.nio.zipfs.allowDotZipEntry=true "apktool.jar" b -o balatro.apk balatro-apk

echo Deleting apktool.jar...
del apktool.jar

echo Deleting balatro-apk folder...
rmdir balatro-apk\ /S /Q

echo Signing APK...
java -jar uber-apk-signer.jar -a balatro.apk

echo Deleting uber-apk-signer.jar...
del uber-apk-signer.jar

echo Deleting unsigned balatro.apk...
del balatro.apk

echo Deleting idsig file...
del balatro-aligned-debugSigned.apk.idsig

echo Renaming apk...
move balatro-aligned-debugSigned.apk balatro.apk